server:
  port: 8081
spring:
  application:
    name: sample-service2
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health